### ISSUE TITLE
missing files for setup.sh

### ISSUE THREAD

**Issue by maks** [petersalomonsen/wasm-git#1]
in setup.sh: where should: `libgit2patchedfiles/*` come from? Is there another repo or step required ?

Also `libgit2/src/transports/http.c` does not seem to exist in the tar file that the script downloads?

**Comment by petersalomonsen** [comment]
I forgot to add them in the initial commit, but they should be there now, so just pull the latest and it should be good. ( you can see them here https://github.com/petersalomonsen/wasm-git/tree/master/libgit2patchedfiles )

`setup.sh` does delete `libgit2/src/transports/http.c` and instead [src/transports/emscriptenhttp.c](https://github.com/petersalomonsen/wasm-git/blob/master/libgit2patchedfiles/src/transports/emscriptenhttp.c) is inserted. This is because we don't want to use the http transport from libgit2 which contains a http parser and uses tcp sockets, but instead use the XmlHttpRequest from the browser, or http in nodejs.

**Comment by maks** [comment]
Great thanks for the quick reply! all working now. :+1:
