### ISSUE TITLE
Add TypeScript types to final bundle

### ISSUE THREAD

**Issue by nikitavoloboev** [petersalomonsen/wasm-git#75]
I would love to get autocomplete on the exposed wasm-git module. 

Not sure how to achieve it best though. I thought perhaps `wasm-git` npm package exposes one `WasmGit` TypeScript type (not sure on name) and then in code you can do:

```
;(async () => {
  const libgit: WasmGit = await libgitPromise
```

This way `libgit` is fully typed at this point. Can type `libgit.` and get completion for `callMain`. Get completions for `callMain` commands too.

To achieve this I guess we can parse C code functions that are defined in `commands` array and create type definitions? Or maybe there's a nicer way.

**Comment by petersalomonsen** [comment]
I think this is beyond the purpose and goals of wasm-git itself, but for sure would be nice as a separate project building on wasm-git. The purpose of wasm-git is first of all to be a port of libgit2 to WebAssembly using Emscripten, and not to introduce any API's on top.

This is also discussed earlier in this issue here: https://github.com/petersalomonsen/wasm-git/issues/30#issuecomment-948984258

**Comment by nikitavoloboev** [comment]
Makes sense. I will just expose types for functions I use for wasm-git, if it becomes an issue I might make a separate repo with types for libgit2 commands.
