### ISSUE TITLE
What does `if (mode === 0o100000 > 0)` mean?

### ISSUE THREAD

**Issue by WebReflection** [petersalomonsen/wasm-git#81]
See https://github.com/petersalomonsen/wasm-git/blob/b336ac60c226c10657d0e94da881916de5ef0877/emscriptenbuild/post.js#L18

I've found this in https://github.com/kiegroup/kie-tools/blob/main/.github/supporting-files/publish_emscripten_fs/post.js

I have no idea why that is not a `if (mode === true)` instead, or if it's a typo, or if it's ever false in general ... proof:

```js
var mode = 0o100000;
if (mode === 0o100000 > 0)
  console.log('this would never be seen');

var mode = 0;
if (mode === 0o100000 > 0)
  console.log('this would never be seen');

var mode = true;
if (mode === 0o100000 > 0)
  console.log('finally a log');
```

As precedence looks like not intentional, or the check against `true` not present, what is the purpose of this patch?

Thank you for clarifying, dropping that, or fixing it in a way that makes sense, because `0o100000 > 0` is always **true**, so it's really not clear what's going on with that `if` statement.

**Comment by petersalomonsen** [comment]
Thanks, this is long ago, but for sure it seems a bit strange this one. I will try removing it and see if the tests still pass.

**Comment by petersalomonsen** [comment]
As you can see the tests run fine without it, and looking at it now, I'm not sure why it was introduced ( even though I wrote the code myself ). Do you know why the authors of kie-tools found the need to copy this into their project?

**Comment by WebReflection** [comment]
nope, but it's a very obscure `if` condition that if somebody doesn't have any background around it might as well just copy/paste it ... I assume that's what happened, but that's just me guessing.

**Comment by tiagobento** [comment]
Hi @WebReflection! You're right. This was introduced when we moved away from Isomorphic Git's Lightning FS in favor of Emscripten's FS. I failed in documenting why we needed to copy this `if` condition, but I probably had a reason back then, as I stripped down everything that I could, and kept only what was necessary. @WebReflection Did you hit any problems because of this line? I'm curious to know how you got there :)

In other notes, I'm following this project closely, as we plan to move away from Isomorphic Git towards a custom-made Git subsystem based on what @petersalomonsen has here, as I think libgit2 itself doesn't seem to be interested in having a JS/WebAssembly library pushed to NPM. I can be wrong on that, and in this case I would love to contribute to a library with a nice JS API backed by libgit2 with WebAssembly.

It's been a while since I had time to investigate, so apologies if I'm making wrong assumptions here.

We didn't do the move yet because we were waiting for https://github.com/libgit2/libgit2/issues/3058 to go in, and now that it did, I still haven't found the time to do it.

Anyway, I'm happy to remove this `if` condition from the code on KIE Tools, but I honestly don't have the time to thoroughly test it right now.

**Comment by petersalomonsen** [comment]
Thanks for your feedback @tiagobento and @WebReflection . Honestly I don't remember what was the reason here for this code, still I can't understand why I wrote this for no reason. I see that the tests are passing in my linked Pull Request, and the tests covers most functionality, and using both NODEFS and MEMFS/IDBFS, so I believe it is safe to remove then.

I will merge the PR then.

Also planning to upgrade to the latest version of libgit2 soon.

Regarding a high level JS API, the scope of wasm-git is primarily to compile libgit2 to WebAssembly, but I have made some high level API implementations now both in [WebAssembly Music](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitclient.js) and also in this [near-account-report](https://github.com/petersalomonsen/near-account-report/blob/main/public_html/storage/gitstorage.js), which maybe could at some point serve the purpose of a high level API (but maybe we want to separate it to another repo/project in order to not bind wasm-git itself to a high level API impl). Would be great though with your contributions and work together on such a high level API.

**Comment by WebReflection** [comment]
@tiagobento 

> Did you hit any problems because of this line?

rather a logical / nonsense problem ... there are parenthesis missing (to group comparison intents) or it doesn't make sense as a check ... probably it was meant to address as `0` some specific number / circumstance but as it is the check is always false for all I could test, unless `mode` is `true` and in such case the check is weird.

> I'm curious to know how you got there :)

I was interested in having FS, PATH and PATH_FS from Emscripten and found your project ... then realized it didn't package it as ESM so I went ahead and pblished [@webreflection/fs](https://github.com/WebReflection/fs#readme) instead which exports out of the box exactly those utilities.

Boyscout rule applied: I've found something weird in the OSS world and I've opened an issue to clarify and hopefully help cleaning up 😇
